server:
  shutdown: graceful

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: false
    async:
      enabled: false
      # Endre default timeout (30000 ms) til 60 sekunder
      timeout: 60000
    # if you want to @ExceptionHandler annotation for custom GraphQLErrors
    exception-handlers-enabled: true
    contextSetting: PER_REQUEST_WITH_INSTRUMENTATION
    tools:
      schema-location-pattern: "**/*.graphqls"
      # Enable or disable the introspection query. Disabling it puts your server in contravention of the GraphQL
      # specification and expectations of most clients, so use this option with caution
      introspection-enabled: true
